CXX = g++
CXXFLAGS = -std=c++17 -O3 -fopenmp -I./include
LDFLAGS = `pkg-config --cflags --libs opencv4`

SRC = main.cpp src/tensor.cpp src/dataset.cpp src/layers.cpp
OBJ = $(SRC:.cpp=.o)
TARGET = cnn_scratch

all: $(TARGET)

$(TARGET): $(OBJ)
	$(CXX) $(CXXFLAGS) -o $@ $^ $(LDFLAGS)

%.o: %.cpp
	$(CXX) $(CXXFLAGS) -c $< -o $@

clean:
	rm -f $(OBJ) $(TARGET)
